### PR TITLE
#110 Add an option to automatically scroll to the first faulty input

### LINKED ISSUE #110: Add an option to automatically scroll to the first faulty input
Hello,

It would be cool that a failed form submit triggers an automatic scrolling to the first faulty input.

Is it possible to have an option to enable this behaviour?

Regards

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fixes #110

### CODE REVIEW

**Comment by jonsamwell** [comment]
Thanks for this.  Could you add a test for the functionality?

**Comment by reda-alaoui** [comment]
Tests added ;)

**Comment by jonsamwell** [comment]
Thanks for this.  I'll release this today

**Comment by jonsamwell** [comment]
Released in version 1.19.1

**Pull request merged**
